In [1]:
 import numpy as np
 arr1=np.array([1,2,3])
 print(arr1*5)

[ 5 10 15]


In [6]:
import numpy as np
arr1=np.array([1,2,3,4,5])
print(type(arr1))
print(arr1.ndim)

arr2=np.array([[1,2,3],
              [4,5,6]
              ])
print(arr2.ndim)

arr3=np.array([
    [ [1,2,3],
      [4,5,6] ],
    [ [6,7,8],
      [9,1,2] ]
])
print(arr3.ndim)

<class 'numpy.ndarray'>
1
2
3


Array Attributesa

In [11]:
#dimention
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

#Shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

#Data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

#size
print(arr1.size)
print(arr2.size)
print(arr3.size)

#selecting a data type for an array
arr=np.array([1,2,3], dtype=np.int8)
print(arr.dtype)
arr=arr.astype(np.int32)
print(arr.dtype)

1
2
3
(5,)
(2, 3)
(2, 2, 3)
int64
int64
int64
5
6
12
int8
int32


In [16]:
# arr=np.zeros((2,3))
# print(arr)
arr=np.zeros_like(arr3)
print(arr)
print(arr.shape)


[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(2, 2, 3)


In [17]:
arr=np.ones_like(arr3)
print(arr)
print(arr.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(2, 2, 3)


In [20]:
arr=np.empty_like(arr3)
print(arr)
print(arr.shape)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(2, 2, 3)


In [24]:
arr=np.full((4,3),True)
print(arr)
print(arr.shape)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]
(4, 3)


  Array creation with random values

In [28]:
arr=np.random.rand(2,3)
print(arr)
print(arr.shape)

[[0.90875967 0.2746712  0.29024123]
 [0.48706561 0.91357269 0.54419737]]
(2, 3)


In [34]:
 arr=np.random.randint(1,10,(2,3))
print(arr)
# print(arr.shape)

[[3 1 6]
 [3 9 3]]


In [35]:
arr=np.random.uniform(1,10,(2,3))
print(arr)

[[9.95941528 8.96529863 2.47255749]
 [9.26033907 3.8446935  4.47704647]]


array creation with range functions

In [42]:
arr=np.arange(1,10,1)
print(arr)
arr=np.arange(1,10,2)
print(arr)
arr=np.arange(1,10,1).reshape(3,3)
print(arr)

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Linear Space

In [49]:
arr=np.linspace(1,10,10)
print(arr)
arr=np.linspace(1,10,11)
print(arr)
arr=np.linspace(1,10,20)
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.   1.9  2.8  3.7  4.6  5.5  6.4  7.3  8.2  9.1 10. ]
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [53]:
arr=np.logspace(0,4,5)
print(arr)
arr=np.logspace(0,4,6)
print(arr)
arr=np.logspace(0,4,6, base=2)
print(arr)
c 

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04]
[1.00000000e+00 6.30957344e+00 3.98107171e+01 2.51188643e+02
 1.58489319e+03 1.00000000e+04]
[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]


Creating matrix for linear algebra

In [54]:
diagonal_mat=np.diag([1,2,3])
print(diagonal_mat)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [57]:
identity_mat=np.eye(3,4)
print(identity_mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


Indexing and Slicing

In [63]:
print(arr1)
print(arr1[2])

arr1[2]=100
print(arr1)

arr1_mod=arr1[1:4]
print(arr1_mod)

[  1   2 100   4   5]
100
[  1   2 100   4   5]
[  2 100   4]


In [68]:
print(arr2)

print(arr2[1][2])

row_0=arr2[0:1,]
row_1=arr2[1:]
print(row_0)
print(row_1)

[[1 2 3]
 [4 5 6]]
6
[[1 2 3]]
[[4 5 6]]


In [69]:
arr1_mod=arr1[1:4].copy()
arr1_mod[2]=200
print(arr1_mod)
print(arr1)

[  2 100 200]
[  1   2 100   4   5]


Advance Indexing

In [70]:
lst=np.array([10,20,30,40])
values=lst[[2,3]]
print(values)

[30 40]


In [72]:
print(arr2)
print(arr2[[0,1],[1,2]])
print(arr2[arr2<2])
print(arr2[arr2>2])

[[1 2 3]
 [4 5 6]]
[2 6]
[1]
[3 4 5 6]


In [79]:
ar=np.array([[1,2,3],[4,5,6]])
for i in ar:
    print(i)
# for i in ar:
#     for j in i:
#         print(j)

for i in np.nditer(ar):
    print(i)

[1 2 3]
[4 5 6]
1
2
3
4
5
6
1
2
3
4
5
6
