In [1]:
import numpy as np
arr=np.random.randint(1,100,size=(10,5))
b=arr.reshape(5,10)
b.shape

(5, 10)

In [2]:
flatten=b.flatten()
flatten.ndim

1

In [8]:
column_flatten=np.ravel(b,order='F')
column_flatten    

# column_flatten=np.ravel(b,order='C')
# column_flatten     

array([58, 74, 30, 39, 27, 77, 63, 30, 42, 14, 92, 43, 47, 74, 49, 29, 87,
       91, 75, 92, 38, 47, 77, 54, 85, 67, 13, 49, 88,  7, 25,  9, 98, 69,
       17, 47, 32, 52, 23, 17,  3, 21, 99, 68, 92, 78, 47,  5,  3, 20])

In [12]:
x=np.random.randint(1,10,size=(2,3))
print(x)
y=np.random.randint(1,30,size=(2,3))
print(y)
r=np.concatenate((x,y),axis=0)
print(r)
c=np.concatenate((x,y),axis=1)
print(c)

[[1 9 8]
 [9 9 2]]
[[15 11 18]
 [14 19 20]]
[[ 1  9  8]
 [ 9  9  2]
 [15 11 18]
 [14 19 20]]
[[ 1  9  8 15 11 18]
 [ 9  9  2 14 19 20]]


In [16]:
a=np.random.randint(1,10,size=(10,))
split=np.array_split(a,3)
print(split)
# split=np.split(a,3)
# print(split)

[array([5, 9, 6, 5]), array([9, 3, 2]), array([8, 2, 2])]
