<a href="https://colab.research.google.com/github/SarthoPramanik1075/Machine-Learning-/blob/main/perceptron_From_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Main Implementation

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [24]:
class Perceptron:
  def __init__(self,eta,epochs):
    self.weights = np.random.randn(3) * 1e-4
    print(f"self.weights {self.weights}")
    self.eta=eta
    self.epochs=epochs

  def activationFunction(self,inputs,weights):
    z= np.dot(inputs,weights)
    return np.where(z>0,1,0)


  def fit(self,X,y):
    self.X=X
    self.y=y

    x_with_bias=np.c_[ self.X, -np.ones( (len(self.X),1))]
    print(f"x_with_bias: {x_with_bias}")

    for epoch in range(self.epochs):
      y_hat = self.activationFunction(x_with_bias, self.weights)
      print(f"Predicted  Value: {y_hat}")

      error=self.y-y_hat
      print(f"Error: {error}")

      #weight Update
      self.weights=self.weights+self.eta*np.dot(x_with_bias.T,error)
      print(f"Updated Weights: {self.weights}")
      print("*****"*10)


  def predict(self,X):
    X_with_bias = np.c_[X, -np.ones((len(X),1))]
    return self.activationFunction(X_with_bias, self.weights)


In [16]:
import pandas as pd
data= {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y"  : [0,0,0,1],
}
AND=pd.DataFrame(data)

X=AND.drop("y", axis=1)
y=AND['y']
y.to_frame()

y
0  0
1  0
2  0
3  1

##Model

In [25]:
model=Perceptron(eta=0.5, epochs=10)
model.fit(X,y)

self.weights [-9.24082838e-05 -2.61254901e-04  9.50369682e-05]
x_with_bias: [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Predicted  Value: [0 0 0 0]
Error: 0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated Weights: [ 0.49990759  0.49973875 -0.49990496]
**************************************************
Predicted  Value: [1 1 1 1]
Error: 0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated Weights: [-9.24082838e-05 -2.61254901e-04  1.00009504e+00]
**************************************************
Predicted  Value: [0 0 0 0]
Error: 0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated Weights: [0.49990759 0.49973875 0.50009504]
**************************************************
Predicted  Value: [0 0 0 1]
Error: 0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [0.49990759 0.49973875 0.50009504]
**************************************************
Predicted  Value: [0 0 0 1]
Error: 0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated 

##Dot Product

In [4]:
import numpy as np

w=np.array([2,2])
x=np.array([2,2])
dot=np.dot(w,x)
dot

np.int64(8)

##Normal Distribution

In [5]:
random= np.random.seed(42)

In [6]:
random_normal=np.random.randn(3)
random_normal

array([ 0.49671415, -0.1382643 ,  0.64768854])

In [7]:
random=np.random.rand(3)
random

array([0.15601864, 0.15599452, 0.05808361])

##Concatation

In [8]:
import pandas as pd
data= {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y"  : [0,0,0,1],
}
AND=pd.DataFrame(data)
AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [9]:
X=AND.drop("y", axis=1) #if drop column then axis=1, drop row then axis=0
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [10]:
y= AND['y']
y.to_frame()

y
0  0
1  0
2  0
3  1

In [11]:
z=len(X)
z

4

In [12]:
#bias=-np.ones(z) #row wised
bias=-np.ones((z,1)) #col wised
bias


array([[-1.],
       [-1.],
       [-1.],
       [-1.]])

In [13]:
bias = np.c_[X, -np.ones((z,1))]
bias

array([[ 0.,  0., -1.],
       [ 0.,  1., -1.],
       [ 1.,  0., -1.],
       [ 1.,  1., -1.]])